import type { JiraClient } from "../jira/jira-client.ts";
import type { JiraIssue } from "../jira/jira-models.ts";
import { gitlabClient } from "../shared.ts";
import logger from "../utils/logger.ts";
import { createClient, promptAndWaitForResponse } from "./opencode-helper.ts";

/**
 * Fix a bug from a Jira issue and create a merge request in GitLab
 * @param jiraClient - The Jira API client
 * @param jiraIssue - The Jira issue containing the bug to fix
 * @param clonePath - Path to the cloned repository
 * @param projectId - GitLab project ID
 * @param projectPath - GitLab project path (e.g., "namespace/project")
 * @returns Summary of the bug fix and created MR
 */
export async function createMRForBugFix(
	jiraClient: JiraClient,
	jiraIssue: JiraIssue,
	clonePath: string,
	projectId: string | number,
	_projectPath: string,
): Promise<string> {
	logger.info(
		{
			issueKey: jiraIssue.key,
			projectId,
			clonePath,
		},
		"Creating MR for bug fix",
	);

	// Create OpenCode client for AI assistance
	const { client: opencodeClient } = await createClient(clonePath);

	try {
		// Step 1: Analyze the bug from the Jira issue
		logger.debug({ issueKey: jiraIssue.key }, "Analyzing bug description");

		const bugDescription = `
Issue: ${jiraIssue.fields.summary}
Description: ${jiraIssue.fields.description || "No description provided"}
Status: ${jiraIssue.fields.status.name}
Priority: ${jiraIssue.fields.priority?.name || "Not set"}
`;

		// Generate a branch name for the fix
		const branchName = `fix/${jiraIssue.key.toLowerCase()}-${Date.now()}`;

		// Get the default branch from project
		const project = await gitlabClient.getProject(projectId);
		const baseBranch = project.default_branch || "main";

		const analysisPrompt = `You are fixing a bug reported in Jira issue ${jiraIssue.key}.

${bugDescription}

Please follow these steps to fix the bug and create a merge request. Do not explain what you are doing - just execute the steps and return the result.

1. **Create a new branch**: Create and checkout a branch named "${branchName}" from "${baseBranch}"
2. **Analyze and fix**: Understand the bug, locate the relevant code files, and implement the fix
3. **Commit your changes**: Stage all changes and commit with this message:
   "fix: ${jiraIssue.fields.summary}
   
   Fixes ${jiraIssue.key}
   
   This fix was automatically generated by Bibus bot based on the bug report."
4. **Push to remote**: Push the branch to the remote repository (origin)
5. **Create merge request**: Use the create_merge_request tool with these parameters:
   - projectId: ${projectId}
   - sourceBranch: "${branchName}"
   - targetBranch: "${baseBranch}"
   - title: "Fix: ${jiraIssue.fields.summary} [${jiraIssue.key}]"
   - description: Use this format:
     ## Bug Fix for ${jiraIssue.key}
     
     ### Original Issue
     ${bugDescription}
     
     ### Fix Summary
     [Your summary of what you fixed and how]
     
     ---
     *This MR was automatically generated by Bibus bot*
     *Jira Issue: ${jiraIssue.key}*
   - labels: ["bot-generated", "bug-fix", "${jiraIssue.key}"]

After completing all steps, your reply will be posted as a comment on Jira issue ${jiraIssue.key}. Provide only:
- The merge request URL (required - this will be posted to the issue)
- One brief sentence describing what was fixed

Work in the current directory: ${clonePath}`;

		logger.info(
			{ issueKey: jiraIssue.key },
			"Requesting AI to fix the bug and create MR",
		);
		const fixSummary = await promptAndWaitForResponse(
			opencodeClient,
			analysisPrompt,
		);

		logger.debug(
			{ issueKey: jiraIssue.key },
			"Bug fix and MR creation completed by AI",
		);

		// Try to link MR back to Jira issue
		// Parse the MR URL from the AI's response (if present)
		const mrUrlMatch = fixSummary.match(
			/https?:\/\/[^\s]+\/merge_requests\/\d+/,
		);
		if (mrUrlMatch) {
			const mrUrl = mrUrlMatch[0];
			try {
				logger.info(
					{ issueKey: jiraIssue.key, mrUrl },
					"Creating remote link in Jira",
				);

				const mrIidMatch = mrUrl.match(/\/merge_requests\/(\d+)/);
				const mrIid = mrIidMatch ? mrIidMatch[1] : "unknown";

				await jiraClient.createRemoteLink(jiraIssue.key, {
					url: mrUrl,
					title: `Merge Request !${mrIid}`,
					summary: `Fix for ${jiraIssue.key}: ${jiraIssue.fields.summary}`,
					icon: {
						url16x16: "https://gitlab.com/favicon.ico",
						title: "GitLab",
					},
					relationship: "fixes",
				});

				logger.info(
					{ issueKey: jiraIssue.key, mrUrl },
					"Remote link created successfully",
				);
			} catch (error) {
				// Don't fail the whole operation if remote link creation fails
				logger.warn(
					{ error, issueKey: jiraIssue.key, mrUrl },
					"Failed to create remote link in Jira, but MR was created successfully",
				);
			}
		} else {
			logger.warn(
				{ issueKey: jiraIssue.key },
				"Could not find MR URL in AI response to create Jira remote link",
			);
		}

		return fixSummary;
	} catch (error) {
		logger.error(
			{
				issueKey: jiraIssue.key,
				error: error instanceof Error ? error.message : String(error),
				errorStack: error instanceof Error ? error.stack : undefined,
				errorName: error instanceof Error ? error.name : undefined,
				errorType: typeof error,
			},
			"Failed to create MR for bug fix",
		);
		throw error;
	}
}
